### ISSUE TITLE
Set up and explain in team meeting what needs to be done

### ISSUE THREAD

**Issue by SebastianZimmeck** [atpratt/COMP333_PS2#1]
@wmccloy based on the current status of the codebase, can you explain in a team meeting with @SilviaMayo and @atpratt what needs to be done? 

(cc'ing @ciscovielma)

**Comment by SebastianZimmeck** [comment]
What are the concrete tasks that need to be addressed?

**Comment by SebastianZimmeck** [comment]
@atpratt is saying:

> I have added you to the git repo online. I believe that our code is making the tables in the SQL Lite DB, as I can see tables named ps2_artists, ps2_users etc. in my DB Browser, but I am not sure how to check to make sure that the information is being inputted correctly (as it evidently is not).

> I have been going through
models: the tables are created in the DB (make migrations has been done)
settings: databases line is correct based on slides
admin: models have been registered
to see if I can isolate the problem but I can not figure out where it is.
Could you give me a little help isolating the problem?

@wmccloy, please hand off the remaining work to @SilviaMayo and @atpratt with an explanation what is still open to do, how your code works, whatever else they need to know to get started ...

**Comment by ghost** [comment]
So far in the Django implementation we’ve created an app titled “ps2,” but we’ll probably want to rename that and make the necessary name changes in the code as we move on to the next homeworks. 
In the “ps2” app folder I’ve written into the following files:

Models.py: created a class (and subsequent database table) for each of the following:
Users: keeps track of app users and their passwords
Artists: contains a song and its corresponding artist
Attributes: primary key is the artist and contains information about their album, release year, genre, and record company
Ratings: links an app user’s username to a song and the rating they’ve given it
I’ve just run “makemigrations” and “migrate” since finalizing the models, so the database should be prepared to communicate with our Django app.
I’m not sure if setting the default for each to “SOME STRING” that Andrew added was necessary.

Urls.py: paths for each of the different functionalities we have

Views.py: created three different views: one for registering a new user, one for retrieving information about the songs a particular user has rated, and one for more information about a particular artist. Imports from both forms.py and models.py.

Forms.py: one form for creating a new user and another for retrieving information from the input (whether it’s a username for ratings or an artist for more attributes)

Templates directory: contains a file called “detail.html” that is supposed to combine a static template with dynamic data.  Generates the user interface we see in the browser and is the outline of what our app is going to look like for the user when presenting them with the info stored in the database

Static directory: contains a css stylesheet that mirrors the one used in the LAMP implementation. It’s not very aesthetically pleasing, so feel free to make it colorful if so desired.

We need to store data in our database like we did in the LAMP implementation because right now our database tables have not been populated.  We also have not created a superuser for the admin portion of the site.  As of right now, our forms are not interacting with the database in the backend.  The views are working and the tables have been created, but there is no interaction with the database.

**Comment by SebastianZimmeck** [comment]
Before you get to work on anything, please make sure that you are all set up on the current status.

When I run your code, I get:

<img width="678" alt="Screen Shot 2022-03-16 at 12 14 47 PM" src="https://user-images.githubusercontent.com/11034003/158636577-5b9a6836-51cd-40f0-8848-48442044fc06.png">

And when trying to register a new user:

<img width="1056" alt="Screen Shot 2022-03-16 at 12 15 57 PM" src="https://user-images.githubusercontent.com/11034003/158636782-87cf52f0-601d-48fc-b7c9-7c2a900f0a53.png">

@SilviaMayo and @atpratt, you should have that running as well. That should be the starting point for your work.

Beyond that GitHub should be set up locally on your computer properly so that you can push changes you make to the codebase. Also, you must be on the MS Teams chat.

If anything of that is missing, you need that get into place first before anything else. 

Do you have any questions?

**Comment by SebastianZimmeck** [comment]
You need to communicate better and more. It is very unclear to me what is going on.

**Comment by SebastianZimmeck** [comment]
You want to organize your work into issue and assign them to each of you so it is clear who does what. Communicate on these issues and close them when they are done. If one of you is facing a problem, it should be discussed in the issue, what has been tried, what are possible solutions, etc.
